excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://carolineloomis.github.io
title: deareverybodyandnobody
tagline: A log of everyday life
description: My awesome new site
paginate: 5